<table class="list" width="100%" cellspacing="0">
	<thead>
		<tr>
			<th>Name</th>
			<th>Role</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
<?php
foreach ($this->users as $user) {?>
<tr>
	<td><a href="<?php echo $this->url(array('action'=>'user-edit','id'=>$user->id))?>" class="name"><?php echo $user->firstname?></a></td>
	<td><?php echo $user->roleAcls?></td>
	<td>
	<a href="<?php echo $this->url(array('action'=>'user-delete','id'=>$user->id))?>" class="control delete" title="Delete">Delete</a>
	<a href="<?php echo $this->url(array('action'=>'user-edit','id'=>$user->id))?>" class="control edit" title="Edit">Edit</a> <a href="/admin/user/user-roles?user=<?php echo $user->id?>" class="control roles inPageForm" title="Roles">Roles</a></td>
</tr>
<?php
 }
?>
	</tbody>
</table>
<a href="<?php echo $this->url(array('action'=>'user-add','id'=>$user->id))?>" class="controlLeft add inPageForm">Add</a>
<script type="text/javascript">
$('.delete').confirm ({message:'Are you sure you want to delete this user?'});
</script>