
<h2>Home</h2>

<table>
<?php foreach($this->checks as $checkSectionTitle => $checkSection) {?>
<tr><td colspan="3"><h3><?php echo $checkSectionTitle?></h3></td></tr>
<?php foreach($checkSection as $checkKey => $check) {?>
<tr>
	<td style="color:<?php echo $check['check']?'green':'red'?>"><?php echo $check['label']?></td>
	<td style="color:<?php echo $check['check']?'green':'red'?>"><?php echo $check['check']?'Yes':'No'?></td>
	<td><?php if (!$check['check']){?><a href="<?php echo $this->url($check['fixUrl'])?>">Fix</a><?php } ?></td>
</tr>

<?php } ?>
<?php } ?>
</table>
